export { createElement, Fragment, createElementNS, dispatchEvent } from './DOM'
export { onDestroy, configure } from './ComponentHost'
export { default as propTypes } from './propTypes'
export { createRoot } from './render'
export { createHost } from './createHost'
export * from './eventAlias'
export * from './Host'